FROM node:22.21.1 AS base

WORKDIR /app

COPY standalone ./
COPY static ./.next/static

ENV NODE_ENV=production
# Uncomment the following line in case you want to disable telemetry during runtime.
ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 14000

ENV PORT=14000

ENV HOSTNAME="0.0.0.0"
