---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-node-go
    tag: 1.21.7-bullseye-node-20

inputs:
  - name: dis-data-admin-ui

outputs:
  - name: build

caches:
  - path: dis-data-admin-ui/node_modules

run:
  path: dis-data-admin-ui/ci/scripts/build.sh
