---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 20.3.1

inputs:
  - name: dis-data-admin-ui

outputs:
  - name: build

run:
  path: dis-data-admin-ui/ci/scripts/build.sh
  