---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.0-bullseye

inputs:
  - name: dis-data-admin-ui

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dis-data-admin-ui/ci/scripts/build.sh
