"use server";

import { cookies } from "next/headers";
import { redirect } from "next/navigation";

import { httpPost, httpPut, SSRequestConfig } from "@/utils/request/request";
import { logError, logInfo } from "@/utils/log/log";
import { getDistributionPath } from "@/utils/url/url";

import { z } from "zod";
 
const versionSchema = z.object({
    quality_designation: z.string().min(1, { message: "Quality designation is required" }),
    release_day: z.string().min(1, { message: "Day is required" }),
    release_month: z.string().min(1, { message: "Month is required" }),
    release_year: z.string().min(1, { message: "Year is required" }),
    release_hour: z.string().min(1, { message: "Hour is required" }),
    release_minutes: z.string().min(1, { message: "Minutes are required" }),
    release_date: z.string().min(1, { message: "A release time and date is required" }),
    distributions: z.array(z.object({
        download_url: z.string().min(1, { message: "A file upload is required" }),
    })).min(1, { message: "A file upload is required" })
});

// check for an error on distrubution and update error message
// zod replies with "Required" for objects
const addUploadFileErrorMessage = (errors) => {
    if (!errors) {
        return;
    } 
    if (errors.distributions) {
        errors.distributions = ["File upload is required"];
    }
    return errors;
};

// check and parse "MultiContent" (e.g. alerts and usuage notes) fields 
const parseMutliContentField = (multiItem) => {
    if (!multiItem || !multiItem.length) return [];

    const parsedItems = [];
    multiItem.forEach(item => {
        const parsed = JSON.parse(item);
        if (parsed.type && parsed.description || parsed.title) {
            parsedItems.push(parsed);
        }
    });
    return parsedItems;
};

/**
 * Updates file metadata for each distribution in a dataset version.
 *
 * @param {object} reqCfg - Request config object generated by SSRequestConfig function.
 * @param {Array<{download_url: string}>} distributions - Array of distribution objects containing download URLs.
 * @param {string} datasetID - The dataset ID.
 * @param {string} editionID - The edition ID.
 * @param {number} versionID - The version number.
 * @returns {Promise<{success: boolean, failures: Array<{download_url: string, status: number|null, error: string|null}>}>}
 *   Resolves with a summary of any failed updates.
 */

const updateDistributionsMetadata = async (reqCfg, distributions = [], datasetID, editionID, versionID) => {
    const fileMetadataUpdateRequests = distributions.map(async (distribution) => {
        const filePath = getDistributionPath(distribution?.download_url);

        if (!filePath) {
            logError("invalid file path", distribution, null, null);
            return { success: false, distribution, status: null, error: "invalid file path" };
        }

        try {
            const response = await httpPut(reqCfg, `/files/${filePath}`, {
                content_item: {
                    dataset_id: datasetID,
                    edition: editionID,
                    version: String(versionID),
                },
            });

            if (response.status >= 400) {
                logError("failed to update file metadata", distribution, response.status, null);
                return { success: false, distribution, status: response.status, error: response.errorMessage };
            }

            return { success: true, distribution };

        } catch (err) {
            logError("error updating file metadata", distribution, null, err);
            return { success: false, distribution, status: null, error: err.toString() };
        }
    });

    const fileMetadataUpdateResponses = await Promise.all(fileMetadataUpdateRequests);
    const failures = fileMetadataUpdateResponses.filter(r => !r.success);

    return { success: failures.length === 0, failures };
};

const doSubmission = async (datasetVersionSubmission, makeRequest) => {
    const reqCfg = await SSRequestConfig(cookies);

    let url = `/datasets/${datasetVersionSubmission.dataset_id}/editions/${datasetVersionSubmission.edition}/versions`;
    if (datasetVersionSubmission.version_id) { url = url + `/${datasetVersionSubmission.version_id}`; }

    let versionResponse = {};
    try {
        versionResponse = await makeRequest(reqCfg, url, datasetVersionSubmission);
        if (versionResponse.status >= 400) {
            return { success: false, code: versionResponse.status };
        }
        logInfo("created dataset version successfully", null, null);
    } catch (err) {
        logError("error saving dataset version", null, null, err);
        return { success: false, code: 500 };
    }

    const versionID = versionResponse.version || datasetVersionSubmission.version_id;
    try {
        const distributionUpdateResponse = await updateDistributionsMetadata(
            reqCfg,
            datasetVersionSubmission.distributions,
            datasetVersionSubmission.dataset_id,
            datasetVersionSubmission.edition,
            versionID
        );
        if (!distributionUpdateResponse.success) {
            logError("one or more file metadata updates failed", distributionUpdateResponse.failures, null);
            return {
                success: false,
                code: 500,
                httpError: "Failed to update file metadata. Please raise a support issue through Slack.",
            };
        }
        logInfo("successfully updated file metadata for distributions");
    } catch (err) {
        logError("error updating file metadata", null, null, err);
        return {
            success: false,
            code: 500,
            httpError: "Failed to update file metadata. Please raise a support issue through Slack.",
        };
    }

    redirect("/series/" + datasetVersionSubmission.dataset_id + "/editions/" + datasetVersionSubmission.edition + "/versions/" + versionID + "?display_success=true");
};

const getFormData = async (formData) => {
    const usageNotes = formData.getAll("usage-notes");
    const parsedUsageNotes = parseMutliContentField(usageNotes);
    const alerts = formData.getAll("alerts");
    const parsedAlerts = parseMutliContentField(alerts);
    const datasetVersion = {
        dataset_id: formData.get("dataset-id"),
        edition: formData.get("edition-id"),
        version_id: formData.get("version-id"),
        edition_title: formData.get("edition-title"),
        quality_designation: formData.get("quality-designation-value"),
        release_day: formData.get("release-date-day"),
        release_month: formData.get("release-date-month"),
        release_year: formData.get("release-date-year"),
        release_hour: formData.get("release-date-hour"),
        release_minutes: formData.get("release-date-minutes"),
        release_date: formData.get("release-date-value"),
        usage_notes: parsedUsageNotes,
        alerts: parsedAlerts,
        distributions: JSON.parse(formData.get("dataset-upload-value")),
        type: "static",
    };
    return datasetVersion;
};

const handleFailedValidation = async (validation, datasetVersionSubmission) => {
    const actionResponse = {};
    actionResponse.success = validation.success;
    actionResponse.errors = validation.error.flatten().fieldErrors;
    actionResponse.errors = addUploadFileErrorMessage(actionResponse.errors);
    actionResponse.submission = datasetVersionSubmission;
    logInfo("failed dataset version validation", null, null);
    return actionResponse;
};

const createDatasetVersion = async (currentstate, formData) => {
    const datasetVersionSubmission = await getFormData(formData);
    const validation = versionSchema.safeParse(datasetVersionSubmission);

    if (!validation.success) {
        return await handleFailedValidation(validation, datasetVersionSubmission);
    }
    return doSubmission(datasetVersionSubmission, httpPost);
};

const updateDatasetVersion = async (currentstate, formData) => {
    const datasetVersionSubmission = await getFormData(formData);
    const validation = versionSchema.safeParse(datasetVersionSubmission);

    if (!validation.success) {
        return await handleFailedValidation(validation, datasetVersionSubmission);
    }
    return doSubmission(datasetVersionSubmission, httpPut);
};

export { createDatasetVersion, updateDatasetVersion, getFormData, handleFailedValidation, updateDistributionsMetadata };
